routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

 Route::get('/register',function(){
   return redirect('/');
 });

 Route::get('/home', 'HomeController@index')->name('home');


 Route::resource('disciplina', 'DisciplinaController');

 Route::resource('aluno', 'AlunoController');

 Route::resource('aluno_nota_disciplina', 'AlunosNotaDisciplinasController');

app/Models/AlunoNotaDisciplina.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class AlunoNotaDisciplina extends Model implements Transformable
{
    use TransformableTrait;

    protected $table = 'alunos_notas_disciplinas';

    protected $fillable = [
        'nota',
        'id_aluno_disciplina'
    ];

    public $timestamps = false;

    /**
     * AlunoNotaDisciplina belongs to Aluno.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function alunoDisciplina()
    {
        // belongsTo(RelatedModel, foreignKey = aluno_id, keyOnRelatedModel = id)
        return $this->belongsTo('App\Models\AlunoDisciplina', 'id_aluno_disciplina', 'id');
    }
}

resources/views/pages/aluno_nota_disciplina/create.blade.php
@extends('layouts.app')

@section('title')
    Cadastrar
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Cadastrar Nota da Disciplina
                </div>

                <div class="panel-body">
                    {!! Form::open(['route' => 'aluno_nota_disciplina.store']) !!}

                        @include('pages.aluno_nota_disciplina.partials.form')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/aluno_nota_disciplina/edit.blade.php
@extends('layouts.app')

@section('title')
    Editar
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Editar Nota da Disciplina
                </div>

                <div class="panel-body">
                    {!! Form::model($nota, ['route' => ['aluno_nota_disciplina.update', $nota->id], 'method' => 'PUT']) !!}

                        @include('pages.aluno_nota_disciplina.partials.form')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/aluno_nota_disciplina/index.blade.php
@extends('layouts.app')

@section('title')
Nota da Disciplina
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12 ">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Lista de Nota da Disciplina
                    <a href="{{ route('aluno_nota_disciplina.create') }}" class="pull-right btn btn-sm btn-primary">
                        Cadastrar
                    </a>
                </div>

                <div class="panel-body">

                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th width="10px">ID</th>
                                <th>Nota</th>
                                <th>Aluno Disciplina</th>
                                <th colspan="3">&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            {{--@foreach($nota as $notas)--}}
                            {{--<tr>--}}
                                {{--<td>{{ $nota->id }}</td>--}}
                                {{--<td>{{ $nota->nota }}</td>--}}
                                {{--<td>{{ $nota->id_aluno_disciplina }}</td>--}}
                                {{--<td width="10px">--}}
                                    {{--<a href="{{ route('aluno_nota_disciplina.show', $nota->id) }}" class="btn btn-sm btn-default">Visualizar</a>--}}
                                {{--</td>--}}
                                {{--<td width="10px">--}}
                                    {{--<a href="{{ route('aluno_nota_disciplina.edit', $nota->id) }}" class="btn btn-sm btn-default">Editar</a>--}}
                                {{--</td>--}}
                                {{--<td width="10px">--}}
                                    {{--{!! Form::open(['route' => ['aluno_nota_disciplina.destroy', $nota->id], 'method' => 'DELETE']) !!}--}}
                                        {{--<button class="btn btn-sm btn-danger">--}}
                                            {{--Excluir--}}
                                        {{--</button>--}}
                                    {{--{!! Form::close() !!}--}}
                                {{--</td>--}}
                            {{--</tr>--}}
                            {{--@endforeach--}}
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/aluno_nota_disciplina/show.blade.php
@extends('layouts.app')

@section('title')
    Vizualizar
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Visualizar Nota da Disciplina
                </div>

                <div class="panel-body">
                    <p><strong>Nota </strong> {{ $nota->nota }}</p>
                    <p><strong>Aluno Disciplina</strong> {{ $nota->id_aluno_disciplina }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection